services:
  file-server:
    image: registry.digitalocean.com/magnus-images/other:file-server-0.2.0
    env_file: '.env'
    container_name: file-server
    networks:
      - social-app
    restart: unless-stopped
    volumes:
      - ./media:/media
networks:
  social-app:
    external: true
