services:
  file-server:
    image: registry.digitalocean.com/magnus-images/file-server:0.1.2
    env_file: '.env'
    container_name: file-server
    networks:
      - social-app
    restart: unless-stopped
    volumes:
      - ./media:/media
networks:
  social-app:
    external: true
